on: 
  push:
    branches:
    - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Setup Golang
        uses: actions/setup-go@v1
        with:
          go-version: 1.24

      - name: Test
        run: go test ./...

  publish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Build and Publish
        uses: opspresso/action-docker@v0.4.0
        with:
          args: --docker --TAG=${{ github.sha }}
        env:
          USERNAME: devbytom
          PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
          DOCKERFILE: "Dockerfile"
          IMAGE_NAME: "devbytom/gcp-idleness-exporter"
          TAG_NAME: ${{ github.sha }}
          LATEST: "true"
